export const socialLinks = [
  {
    id: 'line',
    name: 'line',
    url: '',
    color: '',
    target: '_blank',
    prefix: 'fab',
    interactive: false,
    animation: 'scale',
    fontAwesomeIconType: 'line',
  },
  {
    id: 'wechat',
    name: 'wechat',
    url: '',
    color: '',
    target: '_blank',
    prefix: 'fab',
    interactive: false,
    animation: 'fade',
    fontAwesomeIconType: 'weixin',
  },
  {
    id: 'skype',
    name: 'skype',
    url: 'skype:kaidouya0527?chat',
    color: '',
    target: '_blank',
    prefix: 'fab',
    interactive: false,
    animation: 'shift',
    fontAwesomeIconType: 'skype',
  },
  {
    id: 'gmail',
    name: 'kaidouya0527@gmail.com',
    url: 'javascript:void(0)',
    color: '',
    target: '',
    prefix: 'fas',
    interactive: true,
    animation: 'perspective',
    fontAwesomeIconType: 'envelope',
  },
];