export const socialLinks = [
  {
    id: 'line',
    name: 'ID：chaoyann',
    url: 'https://line.me/ti/p/10XtIqnP94',
    color: '',
    target: '_blank',
    prefix: 'fab',
    interactive: true,
    animation: 'perspective',
    fontAwesomeIconType: 'line',
  },
  {
    id: 'wechat',
    name: 'ID：chaoyann',
    url: 'https://wx.qq.com/',
    color: '',
    target: '_blank',
    prefix: 'fab',
    interactive: true,
    animation: 'perspective',
    fontAwesomeIconType: 'weixin',
  },
  // {
  //   id: 'qq',
  //   name: 'qq',
  //   url: 'http://wpa.qq.com/msgrd?v=3&uin=1391689484&site=qq&menu=yes',
  //   color: '',
  //   target: '_blank',
  //   prefix: 'fab',
  //   interactive: false,
  //   animation: 'perspective',
  //   fontAwesomeIconType: 'qq',
  // },
  {
    id: 'gmail',
    name: 'chaoyann@gmail.com',
    url: 'mailto:chaoyann@gmail.com',
    color: '',
    target: '',
    prefix: 'fas',
    interactive: true,
    animation: 'perspective',
    fontAwesomeIconType: 'envelope',
  },
];